# You can freely (re)use this Travis template to enable CI (Continuous Integration) for your own open font project.
# Your project needs to make use of smith. See https://github.com/silnrsi/smith
# You may need to adjust some variables like user/project and OAuth tokens.
# For documentation on the recommended steps see Font Development Best Practises at http://silnrsi.github.io/FDBP
# More details in the Travis documentation at https://docs.travis-ci.com/user/getting-started
# Enjoy and let us know if you find issues.


language: python
python:
- '2.7'
sudo: true
os: linux
dist: xenial
before_install:
- sudo add-apt-repository -y ppa:silnrsi/smith
- sudo add-apt-repository -y ppa:fontforge/fontforge
- sudo add-apt-repository -y ppa:jonathonf/texlive-2018
- sudo add-apt-repository -y ppa:git-core/ppa
- sudo apt-get update -y

install:
- sudo apt-get install sile python-odf python-odf-tools libjson-perl libtext-csv-perl libharfbuzz-bin -y
- sudo apt-get install smith-font -y --no-install-recommends
script:
- smith configure
- smith build
- smith alltests
- smith fontlint
- smith zip
- smith tarball
- smith release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ks5y+HbUzmWQ37OqQ8NGY7m1JDtaYdHVf2D9uerBHcb+4eHgvev1xT70+HiOFXefwVcnEgb/7qvr+xi5xSJ48NQAUKhfiH8BL9H9QaHRWA4n+yZwRXZSdNsiCh3gdSBxOZTKqUaP1pErYkRlb861zWF6aGxY6fFFJhxSnDmyxguuL4JZdF7WOPrpaLRoEEyA4qzTT6GPblOcmn8hlHEublIW6VfOdFIdXJawZWj0cjmzV1aI3LpJCcXS4wrPPCBTMU0zWW8GmN+VJObSm9Vb7jFraVAJFTbZrrVhGutwTQuQjrS17qIr67R/A0X+oXr/ghy6z3NzzTwNmjJrS4OUzBWbKyLKlnso422QalAgNPcxXrc9LVo5eB6sOnSBi60X8mxM17iXVRr+FGLUGMf62J2DSFCXVMmaTRj76PHZy6McfWNbVWsz9nmqmy6iHa1WwyRD8z65HhPzWMJmqTfVj31/dli6Jt5ZDkwlUO6k4r/bwQ+Nx0Z7Gs2/438MSfHUCOYA0/qbMfx7xodfIq5tbAM967hHS1y8HBFChsmC9gfrxVJQ5USX4i+k11BnFq4W1lmvYD7HrYOMVjiOA+lh7UR+e3y51hvegf2+Wz1rsvrnWcVoHsKrvOLoyQJeCVPnNEw+8T9FmH/A6px0Ohiv+0nJyIcuhHqN0o/sx3tvXcU=
  file_glob: true
  file:
    - results/releases/*
    - results/*.html
    - results/*.pdf
    - results/*.txt
    - results/*err*
    - results/tests/*
  on:
    tags: false
    all_branches: true
    repo: n7s/tonnelier
notifications:
  email: false  # foo@foo-project.org
  irc: false  # "irc.freenode.org#foo-project"
env:
  global:
    secure: mk3i+Q+6vYU6HT06QrWlwoRRAtJXGBPKSKgYgo6fpSbZ2MlMYn3ODDEZuzE6TWTi2vyZrz9xUYdIGlwNwaRUX/fPskQcyOQ5qJn6VQzKsDbN56AanwSYOoCa8QTyRDezVP/r5npEjvJKK9fuacLsLMcltDUJ0pKC+WPT97+hHSPxhmlA7LufPFOivE4vMQgz2SFjNIS9OAEIISpIKSyjPHlBOCvZOtx3bgnnp2xydFfraF4j9ZpgsNV2bfUhLy2jC61XNZ00wtpqANLO5y16iXSsI69UDt1QqBFIQPhBAEEslYYgBTKjhR0jIvclETy+Dhjfb+3h8KVFkEouWqgfgArHwhJP5vZFHjiENJ35dSFXS0iZyv7iwVmGhde9xuFHooDYRQl8xIoGZ4zgY3vpOyRreAMogON65Cp04i2mLhUcgOxY48qWu+4ol6puVt1eZP3ieVZeMIxUhFmbVtVO2x3ITYh51AWXNgAfZeEaSq4Vv9BTTziKfhHub8/+0nf3E1tT/b8UuZQ/brVxxoKLlq8AHECVr6Acmfjn6id3DEW0FKsuCDdoucIoyUg2sQygKgJ0MrkzhYPT71U9jPuGCcPSfTM34jUNh9CY9iqytSsRJ0pPeRRcI2eBzwVhShigE7ZjDQH/R+4hv475snuG0JWaY8DenVqjxKNxqYFCIqQ=
