language: python
python:
    - "2.7"
    #- "3.6"

sudo: true
os: linux
dist: xenial

before_install:
    - sudo add-apt-repository -y ppa:silnrsi/smith
    - sudo add-apt-repository -y ppa:fontforge/fontforge
    - sudo apt-get update -qq  

install:
    - sudo apt install smith-font

script:
    - smith configure
    - smith build
    - smith alltests
    - smith zip
    - smith tarball
    - smith release
    - smith checksums
    - sile documentation/specimen.sil 


branches:
   only:
    - master

notifications:
    email: false
    irc: false



