name: smith

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Display the path
        run: echo ${PATH}
        shell: bash
      
      - name: Install smith toolchain
        run: |
          sudo add-apt-repository -y ppa:silnrsi/smith-py3
          sudo add-apt-repository -y ppa:fontforge/fontforge
          sudo add-apt-repository -y ppa:jonathonf/texlive-2019
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update -q -y 
          sudo apt-get remove *php* *mono* -y 
          sudo apt-get upgrade -q -y 
          sudo apt-get install libjson-perl libtext-csv-perl libharfbuzz-bin -y
          sudo apt-get install smith-font -y --no-install-recommends

          sudo apt-get install python3-pip python3-setuptools -y 
          sudo pip3 install --upgrade git+https://github.com/googlefonts/fontbakery.git@master#egg=fontbakery
      
      - name: configure / build / test / release 
        run: |
          smith configure
          smith build
          smith alltests
          smith zip
          smith tarball
          smith release 
    
