---
name: smith

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Install smith toolchain
        run: |
          sudo add-apt-repository -y ppa:silnrsi/smith-py3
          sudo add-apt-repository -y ppa:sile-typesetter/sile
          sudo apt-get update -q -y
          sudo apt-get remove *php* *mono* *dotnet* -y
          sudo apt-get autoremove -y
          sudo apt-get upgrade -q -y
          sudo apt-get install sile libtext-unicode-equivalents-perl libtext-pdf-perl libio-string-perl libfont-ttf-scripts-perl libfont-ttf-perl libalgorithm-diff-perl libxml-parser-perl grcompiler libtext-csv-perl libjson-perl libharfbuzz-bin -y
          sudo apt-get install python3-pip python3-setuptools -y
          python3 -m pip install --upgrade git+https://github.com/silnrsi/pysilfont.git@master#egg=pysilfont --user
          python3 -m pip install --upgrade git+https://github.com/silnrsi/palaso-python.git@master#egg=palaso --user
          python3 -m pip install --upgrade git+https://github.com/silnrsi/smith.git@master#egg=smith --user
          sudo pip3 install --upgrade git+https://github.com/googlefonts/fontbakery.git@main#egg=fontbakery --user
          pip3 install fontmake --user
          pip3 install MutatorMath --user
          pip3 install Brotli --user
          git clone https://github.com/silnrsi/fontproof
          cd fontproof
          sudo install -m 644 classes/* /usr/share/sile/classes/
          sudo install -m 644 packages/* /usr/share/sile/packages/
      - name: configure / build / test / release
        run: |
          smith configure
          smith build
          smith alltests
          smith ttfchecks
          smith zip
          smith tarball
          smith release
      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: results/*
