name: smith

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Display the path
        run: echo ${PATH}
        shell: bash
      
      - name: Install smith toolchain
        run: |
          apt-get update -q -y
          apt-get install -q -y software-properties-common libterm-readline-gnu-perl
          add-apt-repository -y ppa:silnrsi/smith
          add-apt-repository -y ppa:fontforge/fontforge
          add-apt-repository -y ppa:jonathonf/texlive-2018
          add-apt-repository -y ppa:git-core/ppa
          apt-get update -q -y 
          apt-get install sile python-odf python-odf-tools libjson-perl libtext-csv-perl libharfbuzz-bin -y
          apt-get install smith-font -y --no-install-recommends
      
      - name: configure / build / test / release 
        run: |
          smith configure
          smith build
          smith alltests
          smith zip
          smith tarball
          smith release 
    
